### ISSUE TITLE
Link for settings.xml not working

### ISSUE THREAD

**Issue by samruddh-singhal** [pentaho/data-access#826]
As part of commit - "[BACKLOG-12037] - Mavenize data-access", on the readme page link for settings.xml file is provided (https://github.com/pentaho/maven-parent-poms/blob/master/maven-support-files/settings.xml). But it seems either that file gets deleted or link is not correct.

Please provide the correct link of settings.xml, so that we can build this project using maven.

**Comment by lgrill-pentaho** [comment]
That URL is updated now. https://github.com/pentaho/data-access/blob/master/README.md
